version: '2'
services:
  cron:
    build: .
    environment:
      - PYTHONIOENCODING=UTF-8
    env_file:
      - account-info.env 
    links:
      - redis
    volumes:
      - /usr/share/zoneinfo:/usr/share/zoneinfo
      - /etc/localtime:/etc/localtime
    volumes_from:
      - redis
    restart: always
  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
      - /usr/share/zoneinfo:/usr/share/zoneinfo
      - /etc/localtime:/etc/localtime
    restart: always
volumes:  
  redis_data:
